# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "952a3c31f457198f9731941e9cbc1276"
name = "Suspension Bros Searchalytics"
application_url = "https://chronic-answered-america-even.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "suspensionpro.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://chronic-answered-america-even.trycloudflare.com/auth/callback",
  "https://chronic-answered-america-even.trycloudflare.com/auth/shopify/callback",
  "https://chronic-answered-america-even.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
